---
- name: Generate Hosts File
  hosts: worker
  become: true
  gather_facts: true
  tasks:
    - name: Copy master token
      copy:
        src: ./workertoken.sh
        dest: /join-worker-command.sh
        owner: root
        group: root
        mode: '0777'
    - name: Add new Kubernetes master member
      command: sh /join-worker-command.sh
