---
- name: Generate Hosts File
  hosts: worker
  become: true
  gather_facts: true
  tasks:
    - name: Upgrade all packages
      yum: name=* state=latest
    - name: Executing a command swapoff -a
      command: swapoff -a
    - name: Executing a command sed -i '/swap/d' /etc/fstab
      command: sed -i '/swap/d' /etc/fstab
    - name: containerd.conf
      file:
        path: "/etc/modules-load.d/containerd.conf"
        state: touch

    - name: Copy using inline content
      blockinfile:
          block: |
                overlay
                br_netfilter
          path: "/etc/modules-load.d/containerd.conf"
    - name: Executing a command modprobe overlay
      command: modprobe overlay
    - name: Executing a command modprobe br_netfilter
      command: modprobe br_netfilter

    - name: kubernetes.conf
      file:
          path: "/etc/sysctl.d/kubernetes.conf"
          state: touch

    - name: Copy using inline content
      blockinfile:
            block: |
                net.bridge.bridge-nf-call-ip6tables = 1
                net.bridge.bridge-nf-call-iptables  = 1
                net.ipv4.ip_forward                 = 1
            path: "/etc/sysctl.d/kubernetes.conf"
    - name: Executing a command sysctl --system
      command: sysctl --system
    - name: Executing a command yum remove docker \ docker-client \ docker-client-latest \ docker-common \ docker-latest \ docker-latest-logrotate \ docker-logrotate \ docker-engine runc
      command: yum remove docker \ docker-client \ docker-client-latest \ docker-common \ docker-latest \ docker-latest-logrotate \ docker-logrotate \ docker-engine runc -y

    - name: Executing a command yum update
      command: yum update -y

    - name: Executing a command yum install -y yum-utils
      command: yum install -y yum-utils

    - name: Executing a command yum-config-manager \--add-repo \ https://download.docker.com/linux/centos/docker-ce.repo
      command: yum-config-manager \--add-repo \ https://download.docker.com/linux/centos/docker-ce.repo

    - name: Executing a command yum install docker-ce docker-ce-cli containerd.io docker-compose-plugin
      command: yum install docker-ce docker-ce-cli containerd.io docker-compose-plugin -y
    - name: Executing a command mkdir /etc/containerd
      command: mkdir -p /etc/containerd

    - name: Executing a command containerd config default > /etc/containerd/config.toml
      command: containerd config default > /etc/containerd/config.toml

    - name: Executing a command systemctl restart containerd
      command: systemctl restart containerd
    - name: Executing a command systemctl enable containerd
      command: systemctl enable containerd
    - name: Disable SELinux
      selinux:
        state: disabled

    - name: kubernetes.repo
      file:
          path: "/etc/yum.repos.d/kubernetes.repo"
          state: touch
    - name: Copy using inline content
      blockinfile:
            block:  |
                [kubernetes]
                name=Kubernetes
                baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
                enabled=1
                gpgcheck=1
                repo_gpgcheck=1
                gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
                exclude=kubelet kubeadm kubectl
            path: /etc/yum.repos.d/kubernetes.repo


    - name: Executing a command setenforce 0
      command: setenforce 0
    - name: Executing a command sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
      command: sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config

    - name: Executing a command yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
      command: yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes

    - name: Executing a command systemctl enable --now kubelet
      command: systemctl enable --now kubelet

