---
- name: Generate Hosts File
  hosts: leader
  become: true
  gather_facts: true
  tasks:
    - name: create token file
      file:
          path: "/token.txt"
          state: touch
    - name: Initializing Kubernetes cluster
      shell: kubeadm init --control-plane-endpoint "10.182.0.2:6443" --upload-certs --apiserver-advertise-address 10.182.0.3 --pod-network-cidr 192.168.0.0/16
      register: output
    - name: Storing Logs and Generated token for future purpose.
      blockinfile:
            block:  |
               {{output.stdout}}
            path: /token.txt
    - name: Copying required files
      shell: |
        mkdir -p $HOME/.kube
        sudo cp -f /etc/kubernetes/admin.conf $HOME/.kube/config
        sudo chown $(id -u):$(id -g) $HOME/.kube/config
    - name: Install calico pod network
      command: kubectl --kubeconfig=/etc/kubernetes/admin.conf create -f https://docs.projectcalico.org/v3.18/manifests/calico.yaml
    - name: create token file
      file:
          path: "/mastertoken.sh"
          state: touch

    - name: Get member join token 
      shell: sed -n 73,75p /token.txt
      register: output
    - name: Storing master token.
      blockinfile:
            block:  |
               {{output.stdout}}
            path: /mastertoken.sh
    - name: create worker token file
      file:
          path: "/workertoken.sh"
          state: touch

    - name: Get worker join token
      shell: sed -n 83,84p /token.txt
      register: output
    - name: Storing worker token.
      blockinfile:
            block:  |
               {{output.stdout}}
            path: /workertoken.sh
    - name: copy mastertoken
      become: true
      fetch:
        src: /mastertoken.sh
        dest: ./
        flat: yes
    - name: copy workertoken
      become: true
      fetch:
        src: /workertoken.sh
        dest: ./
        flat: yes

